// Copyright (c) 2026 NextScrum LLC. Apache-2.0 Licensed. Part of nextscrum-specs-kit.
//
// scripts/graph.mjs
//
// Zero-dependency dependency-graph generator. Walks a source tree, extracts
// each file's relative import targets, and emits a Mermaid flowchart. The kit
// describes Blocked/Ready and topological ordering in docs/SPEC-SYSTEM.md
// section 6 but ships no tool; this is that tool, for the module-import view.
//
// Inert until configured: set SRC_DIR_REL to the module root you want to graph.
// RESKIN: set SRC_DIR_REL and OUT_FILE_REL for your layout, then run it.
//
// Run:        npm run graph   (or: node scripts/graph.mjs)
// Self-test:  node scripts/graph.mjs --self-test

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, extname, dirname, resolve } from "node:path";
import { ROOT } from "./rules/_shared.mjs";
import { headerLine } from "./rules/29-ip-headers.mjs";

// RESKIN: the source root to graph (relative to repo root). Empty = inert.
const SRC_DIR_REL = "";
// RESKIN: where to write the generated Mermaid flowchart (a .md file).
const OUT_FILE_REL = "docs/architecture/dependency-graph.md";

const CODE_EXTS = new Set([".mjs", ".cjs", ".js", ".ts", ".tsx"]);
const IMPORT_RE = /(?:import\s[^'"]*?from\s*|require\s*\(\s*|import\s*\(\s*)["']([^"']+)["']/g;
const YEAR = new Date().getFullYear();

/** Extract every static import/require target string from a source blob. */
export function parseImports(source) {
  const out = [];
  let m;
  IMPORT_RE.lastIndex = 0;
  while ((m = IMPORT_RE.exec(source)) !== null) out.push(m[1]);
  return out;
}

/** Only relative imports name files inside the tree we are graphing. */
export function isRelative(spec) {
  return spec.startsWith("./") || spec.startsWith("../");
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (CODE_EXTS.has(extname(entry.name)) && !/\.(test|spec)\./.test(entry.name)) out.push(full);
  }
  return out;
}

function nodeId(p) {
  return p.replace(/[^a-zA-Z0-9]/g, "_");
}

function generate(srcAbs, srcRel) {
  const files = walk(srcAbs);
  const edges = [];
  for (const file of files) {
    const fromRel = relative(srcAbs, file).split(/[\\/]/).join("/");
    for (const spec of parseImports(readFileSync(file, "utf8"))) {
      if (!isRelative(spec)) continue;
      // Resolve the import relative to the importing file, back to a src-relative path.
      let target = relative(srcAbs, resolve(dirname(file), spec)).split(/[\\/]/).join("/");
      if (!/\.[a-z]+$/.test(target)) target += extname(file); // add the importer's ext if bare
      edges.push([fromRel, target]);
    }
  }
  const lines = edges.map(([a, b]) => `  ${nodeId(a)}["${a}"] --> ${nodeId(b)}["${b}"]`);
  const body = lines.length ? lines.join("\n") : "  empty[No relative imports found]";
  return (
    `${headerLine(".md", YEAR)}\n\n` +
    `# Dependency graph (${srcRel})\n\n` +
    `> Generated by \`scripts/graph.mjs\`. Do not edit by hand; re-run \`npm run graph\`.\n\n` +
    "```mermaid\nflowchart LR\n" +
    body +
    "\n```\n"
  );
}

function main(args) {
  if (args.includes("--self-test")) return runSelfTest();

  if (!SRC_DIR_REL) {
    console.log("graph: SRC_DIR_REL not set (RESKIN scripts/graph.mjs). Nothing to do.");
    process.exit(0);
  }
  const srcAbs = join(ROOT, SRC_DIR_REL);
  if (!existsSync(srcAbs) || !statSync(srcAbs).isDirectory()) {
    console.log(`graph: source dir "${SRC_DIR_REL}" not found. Nothing to do.`);
    process.exit(0);
  }
  const outAbs = join(ROOT, OUT_FILE_REL);
  writeFileSync(outAbs, generate(srcAbs, SRC_DIR_REL), "utf8");
  console.log(`graph: wrote ${OUT_FILE_REL}`);
  process.exit(0);
}

// ---------- Self-test ----------

function runSelfTest() {
  let pass = 0,
    failc = 0;
  const expect = (name, actual, expected) => {
    if (JSON.stringify(actual) === JSON.stringify(expected)) {
      pass++;
      process.stdout.write(`  ok ${name}\n`);
    } else {
      failc++;
      process.stdout.write(`  x ${name}\n     expected ${JSON.stringify(expected)} got ${JSON.stringify(actual)}\n`);
    }
  };

  process.stdout.write("scripts/graph.mjs self-test\n");

  expect(
    "parseImports finds import + require",
    parseImports(`import x from "./a.js";\nconst y = require("../b.js");\nimport("./c.js");`),
    ["./a.js", "../b.js", "./c.js"],
  );
  expect("parseImports ignores bare strings", parseImports(`const s = "not an import";`), []);
  expect("isRelative true for ./", isRelative("./a.js"), true);
  expect("isRelative true for ../", isRelative("../a.js"), true);
  expect("isRelative false for package", isRelative("node:fs"), false);

  process.stdout.write(`\nself-test: ${pass} passed, ${failc} failed\n`);
  process.exit(failc > 0 ? 3 : 0);
}

const isMain = process.argv[1]?.endsWith("graph.mjs");
if (isMain) main(process.argv.slice(2));
